package classtask;

import java.sql.Connection;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Scanner;

public class LabTask2 {

	public static void main(String[] args) {
		 String url = "jdbc:oracle:thin:@localhost:1521:orcl";
	     String user = "pranay";
	     String pass = "06072003";

	     try(Scanner rd=new Scanner(System.in)) {
	         // Load the Oracle JDBC driver
	         Class.forName("oracle.jdbc.driver.OracleDriver");
	         
	         // Establish a connection
	         Connection con = DriverManager.getConnection(url, user, pass);
	         
	         Statement stm=con.createStatement();
	     //    String sql = "ALTER TABLE CUSTOMER_INFO MODIFY CUSID NUMBER GENERATED BY DEFAULT AS IDENTITY";
	     //     stm.executeUpdate(sql);
	         while(true) {
	        		System.out.println("-------------Customer Login And Registration--------------");
	        		System.out.println("1.REGISTRATION");
	        		System.out.println("2.LOGIN");
	        		System.out.println("3. EXIT interface");
	        		
	        		System.out.println("Enter your Choice:");
	        		int choice=rd.nextInt();
	        	/*	
	        		 CUSID                                              NUMBER(10)
	        		 CUSNAME                                            VARCHAR2(20)
	        		 CUSPASS                                            VARCHAR2(10)
	        		 CUSFNAME                                           VARCHAR2(20)
	        		 CUSLNAME                                           VARCHAR2(20)
	        		 CUSMAIL                                            VARCHAR2(20)
	        		 CUSPHONE                                           NUMBER(20)  */
	        		 switch(choice) {
	        		 case 1:
	        			
	        			 System.out.println("fill the form..\n");
	        			 System.out.println("Enter ID:");
	        			 int id=rd.nextInt();
	        			 rd.nextLine();
	        			 System.out.println("ENTER CUSTOMER NAME:");
	        			 String name=rd.nextLine();
	        			 System.out.println("ENTER CUSTOMER FIRST NAME:");
	        			 String fname=rd.nextLine();
	        			 System.out.println("ENTER CUSTOMER LAST NAME:");
	        			 String lname=rd.nextLine();
	        			 System.out.println("Enter customer mail:");
	        			 String mail=rd.nextLine();
	        			 System.out.println("Enter phonr number:");
	        			 long phone=rd.nextLong();
	        			 rd.nextLine();
	        			 System.out.println("GENERATE PASSWORD (MAX-length:8 character)");
	        			 String password=rd.nextLine();
	        			 
	        			 
	        			 String insertq="INSERT INTO CUSTOMER_INFO VALUES(?,?,?,?,?,?,?)";
	        			 try(PreparedStatement pre=con.prepareStatement(insertq)){
	        				 pre.setInt(1, id);
	        				 pre.setString(2, name);
	        				 pre.setString(3, fname);
	        				 pre.setString(4, lname);
	        				 pre.setString(5, mail);
	        				 pre.setLong(6, phone);
	        				 pre.setString(7, password);
	        				 
	        				 int rows=pre.executeUpdate();
	        				 if(rows>0) {System.out.println("Customer is added....."); 
	        				 
	        				 
	        				 }
	        				 else System.out.println("FAIL to ADD");
	        			 }
	    	         }
	        	}
	        

	}catch(Exception e) {
		e.printStackTrace();
	}

}
}
